In [ ]:
# разряды в больших числах можно записывать через "_" - так они читаются проще
print(123456789 == 123_456_789)

# константы лучше записывать upppercase`ом - чтобы они отличались от простых переменных
PI = 3.14
LIGHT_SPEED = ...
common_variable = ...

True

In [ ]:
# функции

print('programming'.count('r')) # подсчет кол-ва значений аргумента функции в строке
print('programming'.center(20,'_')) # обрамление строки символами с указанием длины конечной строки
print('Word'.swapcase()) # изменение регистра на противоположный
# .title() VS .capitalize() # первый делает заглавной первую букву каждого слова в строке, второй - первую букву всей строки
print('digit1'.rjust(15, ".")) # дополняет строку слева символами до указанной длины
# .zfill() VS .rjust() # первый заполняет нулями и при указании отрицательного значения наполняет справа (по-умолчанию - слева)

2
____programming_____
wORD

In [ ]:
# переименовать столбцы быстро
df.columns = [col.lower().replace(' ', '_') for col in df.columns]

In [ ]:
# если надо "разрядить" подписи на оси

# import matplotlib.ticker as ticker
ax.xaxis.set_major_locator(ticker.MultipleLocator(50))

In [ ]:
# перевернуть слово/строку (поменять буквы в слове/строке задом наперед)
word = 'hello'
print(word[::-1]) # в данном случае -1 (шаг в срезе строки) означает "взять все символы, начиная с последнего"

olleh

In [ ]:
# создать кортежи из двух списков
# Combine five items from names and three items from primary_types
differing_lengths = [*zip(names[:5], primary_types[:3])]
print(*differing_lengths, sep='\n')

In [ ]:
# посчитать количество упоминаний каждого значения в списке
from collections import Counter
type_counts = Counter([list])
print(type_counts)

In [ ]:
# все уникальные комбинации элементов в списке
from itertools import combinations
combos_obj = combinations(poke_types, 2)
print(type(combos_obj))

In [ ]:
# сравнение значений в списках при помощи set
# Convert both lists to sets
ash_set = set(ash_pokedex)
misty_set = set(misty_pokedex)

both = ash_set.intersection(misty_set) # Find the Pokémon that exist in both sets
ash_only = ash_set.difference(misty_set) # Find the Pokémon that Ash has and Misty does not have
unique_to_set = ash_set.symmetric_difference(misty_set) # Find the Pokémon that are in only one set (not both)

In [ ]:
# итертупли (что бы это ни значило). На самом деле, это быстрый способ обрабатывать df
# Loop over the DataFrame and print each row's Index, Year and Wins (W)
for row in rangers_df.itertuples():
  i = row.Index
  year = row.Year
  wins = row.W
  
  # Check if rangers made Playoffs (1 means yes; 0 means no)
  if row.Playoffs == 1:
    print(i, year, wins)

In [ ]:
# в apply можно использовать и lambda-функции
# Convert numeric playoffs to text by applying text_playoffs()
textual_playoffs = rays_df.apply(lambda row: text_playoffs(row['Playoffs']), axis=1)

**Map reduce**

In [ ]:
# функция map
my_pets = ['alfred', 'tabitha', 'william', 'arla']
uppered_pets = [*map(str.upper, my_pets)]
print(uppered_pets)

['ALFRED', 'TABITHA', 'WILLIAM', 'ARLA']

In [ ]:
# функция filter
scores = [66, 90, 68, 59, 76, 60, 88, 74, 81, 65]
def is_A_student(score):
    return score > 75
over_75 = list(filter(is_A_student, scores))
print(over_75)

[90, 76, 88, 81]

In [5]:
# функция reduce

from functools import reduce
myNumbers = [3, 4, 6, 9, 34, 12]
def custom_sum(first, second):
    return first + second
result = reduce(custom_sum, myNumbers)
print(result)

68

In [6]:
# классная штука с именованием переменной в цикле
for group in [246,247,248]:
    name = 'group_'
    exec(name + str(group))
    name = experiment.query("exp_id == @group")

NameError: ignored

In [ ]:
# подобие f-строки для множественных значений
for i in range(1):
  print( "Element %d from response: %s" % (i+1, response_as[i]) )

In [ ]:
# способ пройтись по строкам датафрейма
for ind in list.index:
  result = re.findall(r'.+сенон.+',list['option'][ind])
  if result != '':
    list_result.append(result)

In [7]:
# посмотреть код функции по ее названию
import inspect
lines = inspect.getsource(foo)
print(lines)

NameError: ignored

In [ ]:
# перевести string в datetime
df['datetime'] = df.apply(lambda row: datetime.strptime(row['str_datetime'], '%b %d, %Y %I:%M:%S %p'), axis=1)
# перевести timestamp в datetime
df['datetime'] = df.apply(lambda row: datetime.fromtimestamp(row['timestamp']), axis=1)

In [ ]:
# склеить два столбца с Nan в один
df['C'] = df['A'].where(df['B'].isnull(), df['B'])

**Импорт данных**

In [ ]:
# импорт данных из csv (параметры)
# сколько строк взять, начиная с какой, есть ли заголовок, и названия полей
vt_data_next500 = pd.read_csv("vt_tax_data_2016.csv", 
                       		  nrows=500,
                       		  skiprows=500,
                       		  header=None,
                       		  names=list(vt_data_first500.columns))
# ошибки в строках при импорте (вкл/выкл предупреждения/поломки)
try:
  # Set warn_bad_lines to issue warnings about bad records
  data = pd.read_csv("vt_tax_data_2016_corrupt.csv", 
                     error_bad_lines=False, 
                     warn_bad_lines=True)
except pd.io.common.CParserError:
    print("Your data contained rows that could not be parsed.")

# настраиваемые нулевые значения
# например, "0" в столбце zipcode теперь будет распознан как NaN
data = pd.read_csv("vt_tax_data_2016.csv", na_values={"zipcode":0})

In [ ]:
# импорт данных из excel (параметры)
# какие листы использовать (можно также по номерам), сколько строк пропустить, какие колонки использовать
survey_responses = pd.read_excel("fcc_survey_headers.xlsx",
                        sheet_name=['2016', '2017'] 
                        skiprows=2, 
                        usecols="AD, AW:BA")

# Load file with Yes as a True value and No as a False value
survey_subset = pd.read_excel("fcc_survey_yn_data.xlsx",
                              dtype={"HasDebt": bool,
                              "AttendedBootCampYesNo": bool},
                              true_values=["Yes"],
                              false_values=["No"])

# работа с датами при импорте: Load file, supplying the dict to parse_dates
survey_data = pd.read_excel("fcc_survey_dts.xlsx",
                            parse_dates={"Part2Start": ['Part2StartDate', 'Part2StartTime']})

# альтернативный способ
df = pd.ExcelFile('battledeath.xlsx').parse('sheetname', usecols=[0], skiprows=[0], names=['Country', 'AAM due to War (2002)'])

In [ ]:
# импорт данных из json (параметры)
df = pd.read_json("dhs_report_reformatted.json", orient='split')

# импорт через API
# Get data about NYC cafes from the Yelp API
response = requests.get("https://api.yelp.com/v3/businesses/search", 
                headers=headers, # см. справку к API. Например, headers = {"Authorization": "Bearer {}".format(api_key)}
                params=params) # см. справку к API. Например, params = {"term": "cafe", "location": "NYC", "sort_by": "rating", "limit": 50, 'offset': 50}
# Extract JSON data from the response
data = response.json()
# Load data to a data frame
cafes = pd.DataFrame(data["businesses"])

# нормализованный json
flat_cafes = json_normalize(data["businesses"],
                            sep="_",
                    		record_path="categories",
                    		meta=['name', 
                                  'alias',  
                                  'rating',
                          		  ['coordinates', 'latitude'], 
                          		  ['coordinates', 'longitude']],
                    		meta_prefix='biz_')

In [ ]:
# загрузка flat-файлов (txt, csv...)
data = np.loadtxt(file, delimiter='\t', skiprows=1, usecols=[0,2])
# получить structured array
data = np.genfromtxt('titanic.csv', delimiter=',', names=True, dtype=None)
d = np.recfromcsv('titanic.csv')
# при помощи pandas
data = pd.read_csv(file, sep='\t', comment='#', na_values='Nothing')

In [ ]:
# SQLalchemy
# Import necessary module
from sqlalchemy import create_engine
# Create engine: engine
engine = create_engine('sqlite:///Chinook.sqlite')
# Save the table names to a list: table_names
table_names = engine.table_names()
# Print the table names to the shell
print(table_names)

# хуевый способ коннектиться к БД
# Open engine connection: con
con = engine.connect()
# Perform query: rs
rs = con.execute('SELECT * FROM Album')
# Save results of the query to DataFrame: df
df = pd.DataFrame(rs.fetchall()) # сколько строк достать (в данном случае - все)
# Close connection
con.close()
# Print head of DataFrame df
print(df.head())

# нормальный способ
# Open engine in context manager
# Perform query and save results to DataFrame: df
with engine.connect() as con:
    rs = con.execute('SELECT LastName, Title FROM Employee')
    df = pd.DataFrame(rs.fetchmany(3)) # сколько строк достать (в данном случае - 3)
    df.columns = rs.keys() # достать названия столбцов из оргинальной таблицы
print(df.head())

# самый пиздатый способ
from sqlalchemy import create_engine
import pandas as pd
# Create engine: engine
engine = create_engine('sqlite:///Chinook.sqlite')
# Execute query and store records in DataFrame: df
df = pd.read_sql_query('SELECT * FROM Album', engine)
print(df.head())

**Работа с Google sheets**

In [ ]:
# для работы с Google sheets
from google.colab import auth
auth.authenticate_user()
import gspread
from oauth2client.client import GoogleCredentials
# для экспорта в Google sheets
from gspread_dataframe import set_with_dataframe

# открываем файлы
gc = gspread.authorize(GoogleCredentials.get_application_default())
worksheet = gc.open(file_name).worksheet(sheet_name)
rows = worksheet.get_all_values()

# вывод результата в Google sheets
result_sheet = gc.open(file_name).worksheet(sheet_name)
set_with_dataframe(result_sheet, df)

Эффективный код

In [ ]:
# создать из объекта лист нечетных чисел, начиная с 1 до 11 (* итерирует по элементам range)
[*range(1,12,2)]
# создать список пронумерованных имен из списка names, начиная с "1"
[*enumerate(names, start=1)]

NameError: ignored

In [ ]:
# посчитать время выполнения операции (можно сохранить в переменную при помощи аргумента "-o")
%timeit -r5 -n10 [*range(51)] #-r - опциональный: кол-во повторений, -n - опциональный: кол-во циклов внутри повторения

# посчитать время выполнения функции построчно
pip install line_profiler
%load_ext line_profiler
%lprun -f функция функция([агрументы])

In [ ]:
# генератор df
from random import uniform
pd.DataFrame({column:[uniform(0.99,1.01) for i in range(10)] for column in ['a','b','c']})

The slowest run took 4.04 times longer than the fastest. This could mean that an intermediate result is being cached.
1000 loops, best of 3: 498 µs per loop

In [ ]:
# нарисовать график скользящего среднего
UK_data.resample("D').CustomerID.nunique().rolling(10).mean().plot()

In [ ]:
# два графика на одной области
# Функция построения сравнительного графика
def plot_AtoB(dfA, dfB, column, date):
    ax.plot(dfA[date], dfA[column], '.-', label='A')
    ax.plot(dfB[date], dfB[column], '.-', label='B')
    xlabels = ax.xaxis.get_ticklabels()
    for label in xlabels:
        label.set_rotation(45)
    ax.grid()
    ax.legend();
# Построение графика
fig, ax = plt.subplots(figsize=(8,4))
ax.set(title='Кумулятивная выручка по группам', xlabel='дата', ylabel='кумул, выручка, ден.ед.')
plot_AtoB(cum_revenue A, cun_revenue_B, 'revenue', 'date')